### ISSUE TITLE
Support for new activity features

### ISSUE THREAD

**Issue by pozm** [EmbarkStudios/discord-sdk#23]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Although the features aren't really new anymore, it would be great to still have the functionality within this library. The two features which i primarily have in mind are the following:
- Asset keys being urls
- Buttons

**Describe alternatives you've considered**
For url asset keys i can bypass the check by setting it not using the method eg:
```rs
let mut assets = Assets::default();
assets.large_image = Some(game_thumbnail.clone());
assets.large_text = Some(game_name.clone());
```
But to get buttons to work i would figure i need to do much more and alter the current source code.

**Additional context**
n/a

**Comment by winrg** [comment]
this should be done now that #30 is merged

**Comment by Jake-Shadle** [comment]
Oops
