### ISSUE TITLE
Box<dyn DiscordHandler> used for no reason

### ISSUE THREAD

**Issue by winrg** [EmbarkStudios/discord-sdk#31]
**Describe the bug**
The impl DiscordHandler trait object stored by `Discord` and its internal handler task is boxed in its current form. As far as I can tell, this is just an unnecessary(albeit minor) performance hit(introduces an unnecessary runtime vtable lookup), and converting it to `impl DiscordHandler` would only serve to improve performance. That being said, if there are legitimate reasons, please let me know!

**Additional context**
[Relevant `Discord` ctor code](https://github.com/EmbarkStudios/discord-sdk/blob/d311db749b7e11cc55cb1a9d7bfd9a95cfe61fd1/sdk/src/lib.rs#L68-L115)
[Relevant `handler_task` code](https://github.com/EmbarkStudios/discord-sdk/blob/d311db749b7e11cc55cb1a9d7bfd9a95cfe61fd1/sdk/src/handler.rs#L28-L156)

**Comment by winrg** [comment]
To avoid breaking changes, an implementation of this could create a `new_impl` method, a non-boxed variant of the current `new` method, and replace the current new method with one which wraps the Box in a simple struct, before delegating to `new_impl`.

**Comment by Jake-Shadle** [comment]
It's using `tokio::spawn` internally which requires a `'static` lifetime, this could be worked around, but honestly it's not worth it.
