### ISSUE TITLE
Unable to connect to \\?\pipe\discord-ipc-XXX

### ISSUE THREAD

**Issue by diniremix** [EmbarkStudios/discord-sdk#37]
**Describe the bug**
on Windows 10, when I run the application, it generates a connection error, using IPC

**To Reproduce**
the application takes as an example this [examples/activity](https://github.com/EmbarkStudios/discord-sdk/tree/main/examples/activity)

**Screenshots**
![](https://i.imgur.com/Vqxmo2j.png)

**Device:**
 - OS: Windows 10 (22H2)
- Rust version: 1.76.0
- Rust toolchain: stable-x86_64-pc-windows-msvc (default)
- visual studio build tools 2022 (v.17.9.2)

**Additional context**
it seems to be related to the use of **socat**, there is an [example](https://github.com/EmbarkStudios/discord-sdk/tree/main/sniff) in this repo but for Gnu/Linux

- [an interesting link](https://github.com/andweeb/presence.nvim/wiki/Rich-Presence-in-WSL#wsl-1)

thanks!

**Comment by Jake-Shadle** [comment]
You need discord to be running.

**Comment by diniremix** [comment]
thank!, it is works!

![](https://imgur.com/QAW3mWQ.png)

two questions before closing this issue...
- Can you explain why it is necessary to have the Discord app running?
- Is it possible to remove the bot name?

**Comment by Jake-Shadle** [comment]
From your example it seems you want to make a discord bot with Rust? This project can't be made to create bots, it's a library for integrating an application with discord. For bot creation you can look at [serenity](https://docs.rs/serenity/latest/serenity/).
