### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by moshen** [EmbarkStudios/discord-sdk#42]
The documentation states:

> Deprecation
This hasn't been officially announced by Discord yet, but the [Voice](https://github.com/EmbarkStudios/discord-sdk#voice), [Lobbies](https://github.com/EmbarkStudios/discord-sdk#lobbies), and [Networking](https://github.com/EmbarkStudios/discord-sdk#networking) functionality will be deprecated and removed sometime in the future. Since only the lobbies functionality has been implemented thus far, we will mark that functionality as [deprecated](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) once it is official.

When following the links in the README to read about these features, it appears that Discord has been redirecting them for a while:

https://discord.com/developers/docs/game-sdk/discord-voice -> https://discord.com/developers/docs/developer-tools/game-sdk

It looks like this information is saved on the internet archive:

https://web.archive.org/web/20240809163158/https://discord.com/developers/docs/game-sdk/discord-voice

Which states:

> The GameSDK's Achievements, Applications, Voice, Images, Lobbies, Networking, Storage, and Store (purchases and discounts) features have been deprecated, and will be decommissioned on May 2, 2023

https://web.archive.org/web/20240729152337mp_/https://discord.com/developers/docs/change-log#gamesdk-feature-deprecation

Do these apis still work in discord-sdk?

Since I've dug up the old documentation would you like a patch to put these links in the README?

**Comment by Jake-Shadle** [comment]
> Do these apis still work in discord-sdk?

If they are decommissioned then they won't work.

> Since I've dug up the old documentation would you like a patch to put these links in the README?

Since they already deprecated and removed those features I'll just remove them altogether since there is no point having any documentation about non-existent features, but thank you for pointing out that they've been removed.
